#CI项目
name: ipq60xx-imm

#CI计划
on:
  # 手动执行
  workflow_dispatch:
  # 默认为utc时间，北京时间需要减去8
  # schedule:
  #   - cron: 0 13 1/7 * *

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: ipq60xx-imm

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: ipq60xx-imm
      #源码
      REPO_SOURCE: immortalwrt
      #源码地址
      REPO_URL: https://github.com/VIKINGYFY/immortalwrt.git
      #源码分支
      REPO_BRANCH: main
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/libWrt/wifi.config

