#CI项目
name: ipq60xx-imm

#CI计划
on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  # 手动执行
  workflow_dispatch:
  # 默认为utc时间，北京时间需要减去8
  # schedule:
  #   - cron: 0 13 1/7 * *

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: ipq60xx-imm

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: ipq60xx-imm
      #源码
      REPO_SOURCE: immortalwrt
      #源码地址
      REPO_URL: https://github.com/VIKINGYFY/immortalwrt.git
      #源码分支
      REPO_BRANCH: main
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/libWrt/wifi.config
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名称
      WRT_SSID: OWRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.10.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无

